# Generated by Django 4.2.7 on 2025-09-15 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated')),
                ('text', models.CharField(help_text='Option text', max_length=500)),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated')),
                ('title', models.CharField(help_text='Poll title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional poll description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the poll accepts votes')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Allow anonymous voting')),
                ('multiple_choice', models.BooleanField(default=False, help_text='Allow multiple option selection')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the poll expires', null=True)),
                ('results_finalized', models.BooleanField(default=False, help_text='Whether final results have been calculated')),
                ('category', models.ForeignKey(blank=True, help_text='Poll category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls', to='polls.category')),
                ('created_by', models.ForeignKey(help_text='Poll creator', on_delete=django.db.models.deletion.CASCADE, related_name='created_polls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoteSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated')),
                ('session_key', models.CharField(help_text='Session identifier', max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Session IP address')),
                ('expires_at', models.DateTimeField(help_text='Session expiry')),
            ],
            options={
                'indexes': [models.Index(fields=['session_key'], name='polls_votes_session_005643_idx'), models.Index(fields=['ip_address', 'expires_at'], name='polls_votes_ip_addr_f8116a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated')),
                ('vote_count', models.PositiveIntegerField(default=0, help_text='Final vote count')),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Vote percentage', max_digits=5)),
                ('rank', models.PositiveIntegerField(blank=True, help_text='Option ranking by votes', null=True)),
                ('option', models.ForeignKey(help_text='Poll option', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='polls.option')),
                ('poll', models.ForeignKey(help_text='Associated poll', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='polls.poll')),
            ],
            options={
                'ordering': ['-vote_count', 'option__order_index'],
            },
        ),
        migrations.AddField(
            model_name='option',
            name='poll',
            field=models.ForeignKey(help_text='Associated poll', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated')),
                ('ip_address', models.GenericIPAddressField(help_text="Voter's IP address")),
                ('user_agent', models.TextField(blank=True, help_text="Voter's user agent")),
                ('option', models.ForeignKey(help_text='Selected option', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.option')),
                ('poll', models.ForeignKey(help_text='Associated poll', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.poll')),
                ('user', models.ForeignKey(blank=True, help_text='Voting user (null for anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['poll', 'created_at'], name='polls_vote_poll_id_579149_idx'), models.Index(fields=['user', 'created_at'], name='polls_vote_user_id_28ba74_idx'), models.Index(fields=['ip_address', 'created_at'], name='polls_vote_ip_addr_888978_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('poll', 'user'), name='unique_user_poll_vote'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('poll', 'ip_address'), name='unique_anonymous_poll_vote'),
        ),
        migrations.AddIndex(
            model_name='pollresult',
            index=models.Index(fields=['poll', '-vote_count'], name='polls_pollr_poll_id_6e0364_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pollresult',
            unique_together={('poll', 'option')},
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['is_active', 'created_at'], name='polls_poll_is_acti_b4c47c_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['category', 'is_active'], name='polls_poll_categor_7c36d6_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['created_by', 'is_active'], name='polls_poll_created_01c672_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['poll', 'order_index'], name='polls_optio_poll_id_4a5000_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('poll', 'order_index')},
        ),
    ]
