# Generated by Django 4.2.7 on 2025-09-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='auto_finalize',
            field=models.BooleanField(default=True, help_text='Automatically finalize when expired'),
        ),
        migrations.AddField(
            model_name='poll',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='When the poll becomes active', null=True),
        ),
    ]
