# Generated by Django 4.2.7 on 2025-09-22 08:17

import polls.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_auto_finalize_poll_starts_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(help_text='Option text', max_length=500, validators=[polls.validators.validate_option_text]),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(help_text='Poll title', max_length=200, validators=[polls.validators.validate_poll_title]),
        ),
    ]
